### ISSUE TITLE
Zoom and attribution out of viewport on iPhone 12 mini

### ISSUE THREAD

**Issue by habi** [openstreetmap-polska/openaedmap-frontend#109]
![image](https://user-images.githubusercontent.com/1651235/209428181-b71f4861-40d2-4a65-bfb6-964c7222769e.png)

On an iPhone mini 12 with iOS 16.1 both the Zoom-Out-Minus and the Attribution-i are hidden out of the viewport.

**Comment by habi** [comment]
![image](https://user-images.githubusercontent.com/1651235/209428236-82fce288-80cf-46da-9e17-bcda2152807a.png)

Also with 'Show top tab bar'.

**Comment by starsep** [comment]
@habi 
Can you confirm whether it has been fixed? Fix was deployed to https://dev.openaedmap.org
Unfortunately I don't have iPhone to test it. 
Firefox iPhone responsive design mode doesn't include bars.

**Comment by habi** [comment]
Both portrait and landscape view are fixed, thanks!

![image](https://user-images.githubusercontent.com/1651235/216140308-db75441c-7f55-4b65-a737-be3ac4dcb4c4.png)
![image](https://user-images.githubusercontent.com/1651235/216140326-309e20c4-401c-4123-b771-ec3d8b3ec504.png)
