### ISSUE TITLE
Add level attribute

### ISSUE THREAD

**Issue by rbovard** [openstreetmap-polska/openaedmap-frontend#117]
Is it possible to add the `level` attribute? It's useful for indoor AED.

**Comment by Ancymonek** [comment]
@rbovard @ttomasz 
Maybe here?

![obraz](https://user-images.githubusercontent.com/16021640/212564004-6af7e60a-2cfb-474c-b8ce-128cd680140b.png)

We can use blank space near 'Inside buidling' yes/no values.

**Comment by rbovard** [comment]
Seems good, thanks. But what will happen if this attribute is set without indoor one?

**Comment by Ancymonek** [comment]
Yes, we need to think over how to handle that cases. It will be a bit confusing to present it like this:
Inside building: _No data_ (level: 1). Maybe at the beginning we will just set it for the objects with indoor = yes/no values?

**Comment by rbovard** [comment]
Good idea!

**Comment by rbovard** [comment]
Thanks @starsep, it's looking great!
