### ISSUE TITLE
Implement partners view

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-frontend#127]
It should be based on https://aed.openstreetmap.org.pl.
![image](https://user-images.githubusercontent.com/2798728/221361443-5cd69301-6be7-464b-bdf7-9137f2e32947.png)
![image](https://user-images.githubusercontent.com/2798728/221361434-a525083e-f8df-4d8f-8a0b-d1e2829b877a.png)

**Comment by wzbartczak** [comment]
That's priority number 1 right now
