### ISSUE TITLE
Map render function is called twice

### ISSUE THREAD

**Issue by p4trykJ** [openstreetmap-polska/openaedmap-frontend#140]
Clicking on a feature calls map render function twice.

Reproduction:
1. Click on a single, not clustered feature.
2. Sidebar opens and logs `Opening left sidebar with action` twice, which means it is being rendered twice.

**Comment by starsep** [comment]
It is caused by [React StrictMode](https://react.dev/reference/react/StrictMode). 
> To help you find accidentally impure code, Strict Mode calls some of your functions (only the ones that should be pure) **twice in development**.

I tested openaedmap.org and log is shown once. If it affects production please reopen
