### ISSUE TITLE
Develop a data standardization scheme for download

### ISSUE THREAD

**Issue by wzbartczak** [openstreetmap-polska/openaedmap-frontend#142]
When downloading AED data for the whole world, it gets messy, so I suggest standardizing the data and reducing the number of columns to a reasonable size

**Comment by starsep** [comment]
@wzbartczak 
Please see https://github.com/openstreetmap-polska/openaedmap-backend/blob/main/backend/data_file_generator.py for lists of tags. Tag needs either be in `TAGS_EXPORTED` or have prefix in `TAGS_PREFIX_EXPORTED`.
So for example `access` and `defibrillator:location:pl` are exported, `access:something` isn't at the moment.
It's not deployed to production yet, we can change list of tags.
I based lists on popular tags & https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddefibrillator

Solved in https://github.com/openstreetmap-polska/openaedmap-backend/commit/3b9ef968a35319cb3241732dc8bf6d19b087c492
