### ISSUE TITLE
Use translated vector tiles

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-frontend#145]
New backend allows to use translated vector tiles. It required providing `lang` argument.
TODO: Check whether all languages on frontend are supported on the backend.
Example url: https://backdev.openaedmap.org/api/v1/tile/3/5/3.mvt?lang=PL

**Comment by Zaczero** [comment]
This would for sure add some strain on the server. I am not sure whether we would want to go with it or not. Possibly in some far future.
