### ISSUE TITLE
Improve AED popup display on mobile devices

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-polska/openaedmap-frontend#149]
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/d9e63215-5d1f-4240-868a-c6e2aa5926da)

..after scrolling to the right:

![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/bb245f9d-5eed-4d3e-9701-0f6f502e7bae)

The footer seems to be the issue here.

**Comment by starsep** [comment]
We will likely reduce number of buttons in the footer. 
That requires UX analysis. Some people pointed out that not every option is necessary there
Short-term solution would be so split buttons in more rows or decrease button size

**Comment by Zaczero** [comment]
> We will likely reduce number of buttons in the footer. That requires UX analysis. Some people pointed out that not every option is necessary there Short-term solution would be so split buttons in more rows or decrease button size

Or just a simple horizontal scroll bar for the footer part.

**Comment by Zaczero** [comment]
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/2cb44d4b-832e-49a6-ace5-95a8a74882e7)

I have just noticed that it's also buggy on desktop.

**Comment by Zaczero** [comment]
Not much is needed to fix this, just 2 CSS rules. It would be nice to merge the 2 card-footers into 1 so there is just 1 scroll bar at the bottom and not in the middle (shared between 2).

![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/de6eb3c1-35f0-42de-931b-98c6a5abafa8)

**Comment by starsep** [comment]
@Zaczero thanks! I tested it on mobile app device and indeed works much better
I still think we should re-think buttons there. Nevertheless the fix is enough to close this issue IMO
