### ISSUE TITLE
GeoJSON download of Germany, France or Spain shows error "string_too_short"

### ISSUE THREAD

**Issue by sd5** [openstreetmap-polska/openaedmap-frontend#150]
When I select for example Germany, France or Spain and try to download the GeoJSON data...

![grafik](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/1437972/f2ff2672-b584-487f-b773-54baca0ff7f1)

...I get this error message:

![grafik](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/1437972/cef0150c-eade-41c4-829c-66733c695af1)

I guess it expects something like `DE` instead of just `D`, `FR` instead of `F`, or `ES` instead of `E`.
Brazil on the other hand works fine (because it has `BR`).

**Comment by Zaczero** [comment]
Looks like something went wrong with the code for Germany etc., I'll fix it very soon today! Thanks!

**Comment by Zaczero** [comment]
Forgot to close the issue, this has been already fixed a few days ago, sorry! :slightly_smiling_face:
