### ISSUE TITLE
Date of survey input clears out on year entry

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-polska/openaedmap-frontend#153]
Input sequence:
<kbd>1</kbd> <kbd>TAB</kbd> <kbd>1</kbd> <kbd>TAB</kbd> <kbd>2</kbd> <kbd>0</kbd> 

https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/7f9be70b-7d15-4c32-a70d-71419969c9ad

**Comment by starsep** [comment]
It's for existing AED, right? Did it have `check_date` tag set?

I just pushed fix (https://github.com/openstreetmap-polska/openaedmap-frontend/commit/89e8a327ed419529f37a5379141be648e7adf296) related to verification date to https://dev.openaedmap.org/
Please confirm whether you can still reproduce. I couldn't

**Comment by Zaczero** [comment]
It's been when adding a new AED. I used Chromium-based browser for this. I don't have DEV OSM account so I'll just test on prod :D.

**Comment by starsep** [comment]
I tried on Chromium and it seems to work alright. Did you have today's date filled as default?

**Comment by Zaczero** [comment]
Here, after a fresh page reload.

https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/6a0c89dd-4d57-463b-aa58-24526e3e94eb

**Comment by Zaczero** [comment]
Działa na prod :-)
