### ISSUE TITLE
Change color schema of access=permissive

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-polska/openaedmap-frontend#156]
Permissive access should be treated almost like public.
I suggest changing the color to lighter green.

Also, I suggest reordering the list:
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/36f5e5e2-86fd-422b-a829-b39be91fe919)

**Comment by starsep** [comment]
Sounds reasonable. Changing it will be easy once we confirm it should work like that.
What do you think? @ttomasz @wzbartczak

**Comment by wzbartczak** [comment]
> Sounds reasonable. Changing it will be easy once we confirm it should work like that. What do you think? @ttomasz @wzbartczak

A good idea!

**Comment by starsep** [comment]
Test location: https://dev.openaedmap.org/#map=18/52.241316/20.932786&node_id=10216462264
Before:
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/2798728/5dddcabc-553e-4657-914b-603d74ec135a)
After:
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/2798728/63f81f61-de3e-486a-85aa-5c139af710de)
