### ISSUE TITLE
Logo is not a link/not clickable

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-polska/openaedmap-frontend#157]
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/fe6cef78-eb0e-41a1-8739-fe246af5faa0)

It's quite common and intuitive to make a website logo clickable, including the image as well. Using href="/", usually, is the way to go about it.

**Comment by shubhamku044** [comment]
can I take this issue?

**Comment by starsep** [comment]
> can I take this issue?

Sure 😄, we are happy to receive contributions. If you need any help don't hesitate to ask

**Comment by shubhamku044** [comment]
okay, then please assign it to me.
