### ISSUE TITLE
Switch to api.openstreetmap.org API host

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap-polska/openaedmap-frontend#171]
Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.

(Is: https://github.com/openstreetmap/operations/issues/951)

In https://github.com/openstreetmap-polska/openaedmap-frontend/commit/2b7c9a8a453d38d763d9154d351dd563bcd97ecf I changed the only explicit url, but there seem to be urls using the base `www.openstreetmap.org` in the `path` parameter. They should be changed too.

cc: @ttomasz

**Comment by starsep** [comment]
Code is at https://github.com/openstreetmap-polska/openaedmap-frontend/blob/main/src/osm.ts
Most of the API calls is done using https://github.com/osmlab/osm-auth
We don't specify host there, only path.

We can fix this line: https://github.com/openstreetmap-polska/openaedmap-frontend/blob/56b1c976ea6b58b19ff493e68595b3705faecdee/src/osm.ts#L26

**Comment by danieldegroot2** [comment]
That is what linked commit in `dev` does, I think.

**Comment by danieldegroot2** [comment]
Since other API calls are done using osm-auth I will close this issue here.
