### ISSUE TITLE
fix buttons/links colours in navbar

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/openaedmap-frontend#18]
language links:
![image](https://user-images.githubusercontent.com/31594210/189479862-a82ee3ee-4dc8-4c77-8b52-eaab648ef6ea.png)

github on hover:
![image](https://user-images.githubusercontent.com/31594210/189479880-86ec7633-8e61-47ea-a266-367a48cf9435.png)
(possibly change it to <a> instead of button?)

**Comment by Coolawik** [comment]
GitHub button is fixed

**Comment by starsep** [comment]
Both issues fixed in 387f939f7f15ce47a1677e8ea669033756ac7250
