### ISSUE TITLE
Preconnect to backend domain

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-polska/openaedmap-frontend#189]
I believe it would significantly improve first time load experience for the users. The application always connects to the backend domain.

```html
<link rel="preconnect" href="https://back.openaedmap.org" />
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preconnect

**Comment by Zaczero** [comment]
Also consider:
tile.openstreetmap.org

**Comment by ttomasz** [comment]
Wouldn't it also work to have frontend and backend under the same domain with path (/api) determining if request is for frontend or backend?

**Comment by starsep** [comment]
> Wouldn't it also work to have frontend and backend under the same domain with path (/api) determining if request is for frontend or backend?

:+1: I always found it odd to have backend on separate subdomain back/backdev.

**Comment by Zaczero** [comment]
Agreed. I'll work on that and let @starsep know when to switch to the new style.

**Comment by Zaczero** [comment]
Backend is ready @starsep

https://back.openaedmap.org/docs
https://openaedmap.org/docs

https://back.openaedmap.org/api/v1/node/1
https://openaedmap.org/api/v1/node/1

Local development procedure remains unchanged. Once the frontend uses primary domain for API requests, I will automatically upgrade all existing AED images to the new schema.

I still think we should preconnect to tile.openstreetmap.org :stuck_out_tongue:.

**Comment by starsep** [comment]
Should https://backdev.openaedmap.org still be used for dev backend?
I agree with preconnecting to tile.openstreetmap.org. Done in https://github.com/openstreetmap-polska/openaedmap-frontend/commit/e3fe8ac13b7a429511e4a3eb572e902c9e9cbff3

Edit: I assume it's https://dev.openaedmap.org/api/v1/node/1 for dev env
