### ISSUE TITLE
Translate title and meta title/description of the website

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-frontend#193]
Add title and meta title/description to translations.
To change parameters in generated HTML use https://vitejs.dev/guide/api-plugin#transformindexhtml
It should use `VITE_DEFAULT_LANG` environment variable.

Change title dynamically on start of application and on language switch.

**Comment by RicoElectrico** [comment]
Right now the tags are not localizable, but I think people can comment with translations:

**Title:** _Open map of Automatic External Defibrillators (AEDs)_
**Meta description:** _Map of AEDs (Automatic External Defibrillators) based on OpenStreetMap data. Our website makes it easy to find an AED defibrillator near you, which can be very helpful in life-threatening situations. AED defibrillators are devices that are used for cardiopulmonary resuscitation of people in cardiac arrest. With our map, anyone can quickly find the nearest defibrillator and help someone in need._

**Comment by starsep** [comment]
I intend to add them to Weblate so they will handled like rest of texts :)
