### ISSUE TITLE
Add Plautdietsch to Language Translation

### ISSUE THREAD

**Issue by CharliePlett** [openstreetmap-polska/openaedmap-frontend#201]
If you add the [Plautdietsch/Low German (PDT)](https://en.wikipedia.org/wiki/Plautdietsch) language then I will translate the title and some other phrases as requested by [@RiceElectrico on Telegram](https://t.me/OpenStreetMapOrg/115351).

**Comment by starsep** [comment]
@CharliePlett
Is it ok to display Google Play/Play Store badges in German?
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/2798728/c78def03-1223-4241-a44d-3b267dbf6f64)

The default is English if badges for particular language are not available.

**Comment by starsep** [comment]
I wasn't able to find this language in Weblate. I requested to add it in https://github.com/WeblateOrg/language-data/issues/1250

**Comment by CharliePlett** [comment]
Yes, the German badge is ok. However Dutch is closer than German if you have a Dutch badge..

**Comment by starsep** [comment]
Dutch version:
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/2798728/28a2c6fc-223c-4368-91f0-aa0346d1f970)
German version:
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/2798728/08a809a8-7a35-45aa-b389-30309525d456)


Which one is preferable?

**Comment by starsep** [comment]
I went with Dutch version. Changing it is easy fyi.

It is available at test server: https://dev.openaedmap.org/pdt/
