### ISSUE TITLE
Remove OSM API fallback

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-polska/openaedmap-frontend#207]
"TODO: remove after fixing https://github.com/openstreetmap-polska/openaedmap-backend/issues/53"

The upstream issue has been resolved.

https://github.com/openstreetmap-polska/openaedmap-backend/issues/53

**Comment by starsep** [comment]
I decided to keep fetchNodeDataFromOsm.
The case is editing AED multiple times in quick succession.
OpenAEDMap could be lagging behind compared to OSM.
Even if it's one minute of delay it's bad UX - because editing would fail
