### ISSUE TITLE
land.html depends on unsafe-inline javascript

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-polska/openaedmap-frontend#208]
Using inline javascripts is unsafe

https://github.com/openstreetmap-polska/openaedmap-frontend/blob/dev/public/land.html

**Comment by Zaczero** [comment]
I think we should switch to single page auth for simplicity. I always found it weird that we need 2 pages to complete authorization.

https://github.com/osmlab/osm-auth?tab=readme-ov-file#example-with-single-page

**Comment by ttomasz** [comment]
> I think we should switch to single page auth for simplicity. I always found it weird that we need 2 pages to complete authorization.
> 
> https://github.com/osmlab/osm-auth?tab=readme-ov-file#example-with-single-page

I agree. At the time of writing the first version it was not documented and my poor JavaScript skills were not enough to make it work without the second html file.

**Comment by starsep** [comment]
@ttomasz 
Can you add redirect urls to OAuth2 applications we are using?
Both dev and production, please.

Currently there is probably only `/land.html` url, we need `/` as well.
Please add new urls, let's keep land.html for now.

Example configuration of my testing, localhost app:
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/2798728/539223c0-e243-4ddf-a204-d3ac49fc8cff)

**Comment by ttomasz** [comment]
Done

**Comment by starsep** [comment]
@ttomasz @Zaczero Could you please test whether logging in/out works correctly on https://dev.openaedmap.org/ for you?
I tested locally and on dev. It worked. 
I'd like to deploy to producation tomorrow if all is good

**Comment by ttomasz** [comment]
Works for me. Though every time it asks to confirm permissions not sure if it was that way before.

**Comment by starsep** [comment]
It works the same way on production for me.
Yeah, I do remember it not asking every time.
I changed some osm-auth settings. Either that or something changed on OSM side
