### ISSUE TITLE
Photo hosting location

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap-polska/openaedmap-frontend#218]
### Current behaviour
Where is actual hosting (not display) happening? Is photo being uploaded to local server and/or wikimedia commons and/or others?
(note, this hosting location may change in the future)

### Expected behaviour
Mention if the photo is uploaded to any other service, below (and in privacy policy if there is one).

![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/67521919/c5e6390a-d137-4928-8788-18aed6ff11eb)

**Comment by starsep** [comment]
Currently photo is only uploaded to our backend server.
At the moment we don't have plans to change that.
I feel that current text is correct but perhaps not explicit.

Could you suggest text which would make it clearer?
Note we don't want to make long descriptions here

**Comment by Zaczero** [comment]
Perhaps:
hosted by us **and** are licensed under

Without this and, the text reads as if there were other hosting providers.

**Comment by danieldegroot2** [comment]
> hosted by us **and** are licensed under

I would suggest
'All AED photos **are** hosted by us **and** are licensed under'
