### ISSUE TITLE
add meta and opengraph html tags

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/openaedmap-frontend#22]

**Comment by Zaczero** [comment]
_Kopiuje tutaj bo prosiłeś_

jak zmienię język na polski np. to cały czas w HTML jest lang="en" co może psuć tłumaczenie stron w niektórych przeglądarkach. javascript powinien zmienić ten tag dynamicznie

```js
document.documentElement.setAttribute("lang", languageCode);
```
