### ISSUE TITLE
Document Photo API terms of use

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap-polska/openaedmap-frontend#223]
Other applications may want to display/download pictures from OpenAEDMap (e.g. MapComplete).
It may be useful to document usage terms for photo API (i.e. maximum number of requests allowed).
(though usually they will do so from URL on single OSM object and cache the request.)

Also, does image stay hosted if no longer used in OSM? If so, for how long?

(given [there are no plans to host images elsewhere](https://github.com/openstreetmap-polska/openaedmap-frontend/issues/218#issuecomment-2000459640).)

**Comment by Zaczero** [comment]
We don't have any hard limits on number of requests (it's fair use). The userbase is not significant and I don't think it's worth setting up atm. We usually have 2-stage cache system (Cloudflare+Varnish) so the requests are pretty lightweight. Cloudflare may eventually block abusive clients.

> Also, does image stay hosted if no longer used in OSM? If so, for how long?

Currently, there is no cleanup system for unused images (except for manually reported ones). I would say it's very low priority. Perhaps, that's something we could think about if we grow further and it starts becoming a real issue. Today we are talking just megabytes of wasted space.

**Comment by danieldegroot2** [comment]
Closing as not planned. Feel free to re-open when needed.

**Comment by Zaczero** [comment]
No problem and thank you! It's important that we consider such issues from time to time. I like how your questions are well thought out.
