### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [openstreetmap-polska/openaedmap-frontend#226]
Dear All,

I have [translated OpenAEDmap into Hungarian](https://hosted.weblate.org/projects/openaedmap/website-translation/hu/): you might consider to deploy it to [openaedmap.org](https://openaedmap.org/).
Cheers

Gábor

**Comment by starsep** [comment]
Thanks!

There is Hungarian version on test server: https://dev.openaedmap.org/hu/

I will deploy to production tomorrow. On production missing texts will be in English

**Comment by starsep** [comment]
Thanks again!
Deployed to production: https://openaedmap.org/hu/
