### ISSUE TITLE
Uk data quality issues

### ISSUE THREAD

**Issue by cuddawudda** [openstreetmap-polska/openaedmap-frontend#227]
Where is the uk data sourced from and how is it validated / reviewed?

eg there is a  defibrillator shown at Whitchurch library, Cardiff. But this is no longer present. 

There is a more accurate map of uk defibrillators. If somebody used the https://github.com/openstreetmap-openaedmap they may try to get a defib that is no longer in place with potentially life threatening consequences. 
i understand the need for a map where there is no better option in place, but think that having a map for the uk that is out of date is potentially dangerous.

**Comment by starsep** [comment]
All data displayed in OpenAEDMap is coming from OpenStreetMap globally.
We don't have any specific UK dataset.

Editing data on our website will modify OpenStreetMap database

**Comment by starsep** [comment]
Power of OpenStreetMap is that anybody can fix the issues.

If you are aware of high quality AED registry available on compatible license please let us know.
We could consider importing new locations and/or validating existing ones with support of UK OSM community.

I am gonna close this issue as it is not currently actionable.

**Comment by cuddawudda** [comment]
Showing incorrect data (as it does for my location) is a lot etuslly serious and life threatening issue. 
there are datasets in the uk that are managed and high quality. 
openstreetmap should not be showing this dataset if it is known that it is lower quality then other sources.

**Comment by Zaczero** [comment]
OpenStreetMap is operated by volunteers (ordinary everyday people). Each country usually has their own dedicated community and I believe if you bring up this issue to the UK community and point out some examples, this will be investigated. Perhaps someone imported lots of AEDs without reviewing them properly (which is not allowed) or they are so old that they should be re-reviewed.

That's a good place to start:
https://community.openstreetmap.org/c/communities/uk/86

Hope that helps!

**Comment by starsep** [comment]
Could you elaborate on what those datasets in the UK are?
What is license of the data and who is managing it?

> openstreetmap should not be showing this dataset if it is known that it is lower quality then other sources.

I am not sure what you mean. OpenStreetMap **is** our data source/dataset.
We are bound by Open Database License and can't use incompatible datasets.
[citation needed] for lower quality.

**Comment by cuddawudda** [comment]
This is the uk dataset I referred to
https://www.defibfinder.uk/

**Comment by starsep** [comment]
Thanks!
Considering it uses [Circuit](https://www.thecircuit.uk/) which looks like official national AED registry in UK I suspect their quality is indeed better than OpenStreetMap in UK.

It's possible to download data at https://www.bhf.org.uk/defibdata
According to infographic they have 96776 AEDs. In Excel file I see 92890 rows.

> I understand that I cannot use the data for commercial purposes
> I understand that I cannot use the data in the creation of an App or map for the public

Suggests that data is not available on compatible license with OpenStreetMap.

**Comment by Zaczero** [comment]
Some services will let OSM use their data if you ask them kindly :slightly_smiling_face:.

Also, *"I understand that I cannot use the data in the creation of an App or map for the public"*, what a weird thing to say.
