### ISSUE TITLE
Support displaying panoramax-images

### ISSUE THREAD

**Issue by pietervdvn** [openstreetmap-polska/openaedmap-frontend#228]
Hi,

As MapComplete is moving towards Panoramax and away from Imgur, it would be nice if OpenAEDMap supported showing those images as well.

Those images are linked with the `panoramax`-key, containing a hash. Querying this on `https://api.panoramax.xyz/api/search/?ids=<hash>` ([example](https://api.panoramax.xyz/api/search/?ids=0e504d96-6311-49af-8e0d-5e1e9de74890)) will give you a .json. Using `features[0].assets.sd` will contain the source of the image to display.

**Comment by Zaczero** [comment]
Added in https://github.com/openstreetmap-polska/openaedmap-backend/commit/c035154316ac2108e8b28ec58524527c97f2de5d

**Comment by thibaultmol** [comment]
That was quick wow!

One thing: it seems like the code doesn't check for `panoramax:0=` , `panoramax:1=` and such.
For example here: https://www.openstreetmap.org/node/11734218691
it only shows one image on aedmap

**Comment by Zaczero** [comment]
OpenAEDMap only supports one image per AED at the moment

**Comment by danieldegroot2** [comment]
> One thing: it seems like the code doesn't check for `panoramax:0=` , `panoramax:1=` and such. For example here: https://www.openstreetmap.org/node/11734218691 it only shows one image on aedmap

Ref #230
