### ISSUE TITLE
add language switcher for mobile visible next to hamburger menu

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/openaedmap-frontend#24]
![image](https://user-images.githubusercontent.com/31594210/189494560-13d7d88e-bf46-43a2-9285-a1747ee516bc.png)
similar to desktop version:
![image](https://user-images.githubusercontent.com/31594210/189494657-3e01d422-7777-46d5-a9ca-1e3d7bd15faf.png)
but maybe no icon and just two letter language codes and arrow?

**Comment by Ancymonek** [comment]
@ttomasz i've just commited on /dev new changes addressing this issue - https://github.com/openstreetmap-polska/openaedmap-frontend/commit/80a5441406b51572b70b7dc7a84a481fa2051eb0

Take a look. It isn't perfect, but i think it's better than previous solution

**Comment by Ancymonek** [comment]
![obraz](https://user-images.githubusercontent.com/16021640/198850532-3cf0fde1-d865-4e5b-a87d-f84accf21290.png)
I've just checked on mobile and it doesn't look good

**Comment by ttomasz** [comment]
continued in #63
