### ISSUE TITLE
use compact formatting for large numbers

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/openaedmap-frontend#26]
e.g. 3.8k instead of 3800
can round down to nearest 100

investigate whether it can be done in maplibre gl js style or if it needs to be formatted in backend

**Comment by caspg** [comment]
I couldn't find a way to format numbers on the frontend, maybe it has to be handled on the backend. On the frontend though, we can use "steps" and increase radius for clusters with greater numbers. 

@ttomasz Let me know you want me to submit PR with different radius. Imo there should be different radius even with compact number format.

Btw, some of the clusters don't have values. The same issue is on the production site.

<img width="944" alt="Screenshot 2022-09-18 at 15 59 49" src="https://user-images.githubusercontent.com/10419439/190910805-70ff1b42-cdfe-4602-b310-fc819b471938.png">

**Comment by caspg** [comment]
Looks that values are not missing. It looks that Maplibre is hiding them when there is some overlapping.

**Comment by ttomasz** [comment]
I agree with different sizes for radius. It's a lot of work to test different styles so it wasn't a priority for me but that is something we definitely should try.

I don't know if clustering algorithm is going to be the same with new backend so we may need to tweak the style in the future.

**Comment by ttomasz** [comment]
this will be available from new backend as `point_count_abbreviated` field

**Comment by ttomasz** [comment]
added in 99d5aa0d4a5fdc47401170c1a14957718adcd1b4
