### ISSUE TITLE
Set up a translation project in some collaborative tool

### ISSUE THREAD

**Issue by stefanb** [openstreetmap-polska/openaedmap-frontend#29]
As more languages are added it becomes harder to track what changed and in which languages some strings need to be added or updated.

I am very satisfied with WebLate - https://hosted.weblate.org/

**Comment by ttomasz** [comment]
I tried setting it up https://hosted.weblate.org/projects/openaedmap/

maybe missing ssh access keys? didn't see that options in the place that docs described. Not sure if it's going to go for fork or fail to push commits, I guess we'll have to modify some string and see.

waiting on approval for Libre plan

**Comment by stefanb** [comment]
It can push directly to the repository if you invite @weblate as a contributor

**Comment by stefanb** [comment]
I have added one in Spanish: https://hosted.weblate.org/translate/openaedmap/website-translation/es/?checksum=8a658a7f82f9559d

**Comment by stefanb** [comment]
You can trigger the push manually on https://hosted.weblate.org/projects/openaedmap/website-translation/#repository or shorten the quiet time to only an hour before WebLate decides to pus on its own.

**Comment by ttomasz** [comment]
Ok I added the bot to project and it can push to repo. We'll need to update README.MD.

**Comment by stefanb** [comment]
Yes, perhaps also add these widgets:
[![Translation status](https://hosted.weblate.org/widgets/openaedmap/-/website-translation/svg-badge.svg)](https://hosted.weblate.org/engage/openaedmap/)

[![Translation status](https://hosted.weblate.org/widgets/openaedmap/-/website-translation/multi-auto.svg)](https://hosted.weblate.org/engage/openaedmap/)

See https://hosted.weblate.org/widgets/openaedmap/

**Comment by ttomasz** [comment]
Good idea :) added.
