### ISSUE TITLE
add better description to "about" modal

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/openaedmap-frontend#30]
![image](https://user-images.githubusercontent.com/31594210/189773785-a21b835c-84ac-45cb-91c3-b98270db2f84.png)

**Comment by ttomasz** [comment]
@wzbartczak suggestions?

**Comment by Coolawik** [comment]
#33 
Something like that or need to be longer?

**Comment by danieldegroot2** [comment]
https://github.com/openstreetmap-polska/openaedmap-frontend/commit/658325eb9247f00f1d05ad3e69b1c66cdddb25a6
Made minor changes to the English translation. Also, added the Dutch translation via Weblate based on this new version.
