### ISSUE TITLE
Prettier support

### ISSUE THREAD

**Issue by caspg** [openstreetmap-polska/openaedmap-frontend#45]
What do you think about adding [Prettier](https://prettier.io/) config and auto-formatting existing code?

**Comment by ttomasz** [comment]
Good idea :)

**Comment by caspg** [comment]
@ttomasz Any style guide do you have in mind? Maybe we should just use default one.

**Comment by ttomasz** [comment]
Default settings should be a good start. We can tweak whatever we don't like later. One thing that I'd like is to set acceptable max line length at 110 chars at least preferably 120.
