### ISSUE TITLE
Add buttons to open Google Maps and OSM map navigation

### ISSUE THREAD

**Issue by caspg** [openstreetmap-polska/openaedmap-frontend#49]
There should be buttons that open Google Maps and OSM map navigation. It should be visible in the popup details. 

Similarly to https://dopomoha.pl/en/#map=4.26/53.38/20.81
<img width="422" alt="Screenshot 2022-09-20 at 08 11 55" src="https://user-images.githubusercontent.com/10419439/191180764-7ef4671a-b12d-45ab-b9c9-fbac5feb0ed7.png">

**Comment by Vinayakkamble07** [comment]
Hi, can I try this? I'm a beginner and would like your help to fix this issue.

**Comment by ttomasz** [comment]
Go ahead. Relevant part of code from dopomoha.pl to provide an example https://github.com/openstreetmap-polska/ua-2022-map/blob/main/templates/map.js#L435

**Comment by Vinayakkamble07** [comment]
Will try it ASAP!!!

**Comment by starsep** [comment]
@Vinayakkamble07 How it's going :)? Feel free to make a draft pull request even it's not ready, perhaps I can help.

**Comment by Vinayakkamble07** [comment]
@starsep would love your help on this .Finding it difficult to solve this issue.

**Comment by starsep** [comment]
It's hard to help without some details.
Are you able to run project locally? 
Do you have experience with HTML/CSS/React/JavaScript?

Those buttons should in AED popup details, somewhere on the bottom.
Example link: https://openaedmap.org/#map=17/51.158873/21.649783&node_id=9437937877
Footer is defined here: https://github.com/openstreetmap-polska/openaedmap-frontend/blob/dev/src/components/sidebar-left.js#L94-L98

![image](https://user-images.githubusercontent.com/2798728/193454062-d1b47ff9-58d3-465d-9fba-1471de7c4ecb.png)

**Comment by Vinayakkamble07** [comment]
Yes I'm able to run the project . But I'm unable to write the required code
.
