### ISSUE TITLE
investigate dev build ignoring NODE_ENV

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/openaedmap-frontend#52]
on dev env there should appear "debug" language added conditionally in i18n.js

**Comment by caspg** [comment]
https://create-react-app.dev/docs/adding-custom-environment-variables/

There is also a built-in environment variable called NODE_ENV. You can read it from process.env.NODE_ENV. When you run npm start, it is always equal to 'development', when you run npm test it is always equal to 'test', and when you run npm run build to make a production bundle, it is always equal to 'production'. **You cannot override NODE_ENV manually. This prevents developers from accidentally deploying a slow development build to production.**


---

I would define a new variable to indicate if we are running the app on prod or dev. Something like: `REACT_APP_IS_DEBUG` (react-scripts will embed env vars starting with REACT_APP_ for us automatically).
