### ISSUE TITLE
Fix info after adding aed

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/openaedmap-frontend#61]
![image](https://user-images.githubusercontent.com/31594210/193430121-ec6bc21a-f470-43b7-8e7a-b09a33a3fddc.png)

**Comment by danieldegroot2** [comment]
Just for the sake of it, showing two possible solutions provided on StackOverflow here:
1. [Property binding](https://github.com/openstreetmap-polska/openaedmap-frontend/blob/086ed6363268f9403f8bae1d8ef03308586922e7/src/components/modal.js#L22) ([answer](https://stackoverflow.com/a/62497036))
2. [Escape the forward slash in end HTML tags](https://github.com/openstreetmap-polska/openaedmap-frontend/blob/a7e511747e6a8e6dc4b500dbb33450ae6547e1ed/public/locales/en/translation.json#L67) ([answer](https://stackoverflow.com/a/55972942))
