### ISSUE TITLE
List of languages is not collapsible on mobile

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-frontend#63]
List of languages is not collapsible on mobile. It should either collapse or work like dropdown.
Tested on Firefox forks on Android and on Linux with mobile mode.
Implemented in https://github.com/openstreetmap-polska/openaedmap-frontend/blob/dev/src/components/languageSwitcher.tsx
Screenshot for context, chevron button does nothing.
![image](https://user-images.githubusercontent.com/2798728/193929352-c909bfdd-c326-46bf-87b4-1abd207dcc51.png)

**Comment by ttomasz** [comment]
Mobile language switcher works fine but regular language switcher which may be visible on tablets or higher resolution phones does not respond to touch in firefox responsive mode.

Additionally mobile language switcher on mobile does not always fit on screen:
![image](https://user-images.githubusercontent.com/31594210/207445920-f25a5a72-7f54-4b97-8b11-a1ab272cc494.png)

**Comment by Zaczero** [comment]
![image](https://github.com/openstreetmap-polska/openaedmap-frontend/assets/10835147/b0737a49-12f4-4ba1-8b34-b6a1c9fec67c)

This has been resolved
