### ISSUE TITLE
Crash with opening_hours = PH off

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-frontend#71]
Example AED: https://openaedmap.org/#map=17/53.46609/18.74759&node_id=9654446743

We should configure opening_hours library: https://github.com/opening-hours/opening_hours.js/#library-api
Also library shouldn't crash the app, I propose displaying `opening_hours` as is when lib cannot parse it.

**Comment by ttomasz** [comment]
done
