### ISSUE TITLE
Handle opening_hours text

### ISSUE THREAD

**Issue by starsep** [openstreetmap-polska/openaedmap-frontend#72]
Example AED: https://openaedmap.org/#map=19/51.12289/17.05204&node_id=9372773571
There is text in `opening_hours`, Closed shouldn't be displayed
![image](https://user-images.githubusercontent.com/2798728/195412941-8451e225-2dc0-49c7-8e9b-c720f6839e09.png)

**Comment by Ancymonek** [comment]
Fixed on dev

**Comment by starsep** [comment]
Fixed in 3f590b7c9be4955ad7bc7d7dcd471692cbe6e26b. Thanks!
