### ISSUE TITLE
Permissive access icon

### ISSUE THREAD

**Issue by Coolawik** [openstreetmap-polska/openaedmap-frontend#77]
Now permissive access icon on map looks like unknown access icon.

![appaint](https://user-images.githubusercontent.com/106607132/197590037-4d1f55b0-8dec-4a3b-a158-1cbcf8cb9576.jpg)

**Comment by ttomasz** [comment]
Was this updated or is this still a bug?

**Comment by Coolawik** [comment]
@ttomasz no :(
![image](https://user-images.githubusercontent.com/106607132/209856819-70eeaee4-9cb5-4422-bad7-b1ed6c9dd908.png)

**Comment by ttomasz** [comment]
I don't know what `access=permissive` means and what should the icon look like. I made PR #111 that shows what should be changed to add separate icon. If someone wants to continue working on that then fell free to do so.

**Comment by Coolawik** [comment]
Definition of "access=permissive" on OSM Wiki is: "An object /AED/, is open for general public use, but access is not protected by law. An owner of the object, or way, may revoke access without following a legal process."
