### ISSUE TITLE
'Spritezero-cli' dependency issue when trying to install in local env

### ISSUE THREAD

**Issue by Ancymonek** [openstreetmap-polska/openaedmap-frontend#80]
Recently added "@beyondtracks/spritezero-cli": "^2.3.1",  dependency tries to install mapnik, which seems to doesn't work on Windows. I've spent a lot of time installing dependencies (like C++ and Visual Studio) to make it work but i lost this battle. After deleting `@beyondtracks/spritezero-cli": "^2.3.1",` from package.json and run `npm install` it works like a charm. 

![obraz](https://user-images.githubusercontent.com/16021640/198373023-d660893e-3872-420c-b0f2-5082190a699f.png)

PS It works fine in dev container.

**Comment by ttomasz** [comment]
It should probably be in devDependencies but that won't solve it for this issue. Seems like they have a lot of issues with missing binaries https://github.com/mapnik/node-mapnik/issues . Not sure what to do about it since it's needed only for generating sprites which is something that will be done very rarely when icons change.

**Comment by ttomasz** [comment]
We could remove it but then generating sprites will be more annoying :sweat_smile:

**Comment by Ancymonek** [comment]
@ttomasz  https://github.com/mapnik/node-mapnik/issues/848

**Comment by ttomasz** [comment]
maybe we could leverage something like this https://github.com/macteo/spritezero-docker (or create our own simple docker image) but someone would need to test using that in node script in package.json

**Comment by ttomasz** [comment]
or bake the dependency it into .devcontainer since i'm using mostly that and provide instructions if someone wants to install it manually on their system :sweat_smile:
or try using older version that windows supports :shrug:

**Comment by starsep** [comment]
Since 38dafb948528068b927fbbc8b3612083e351b2fb it has been moved to `devDependencies`
