### ISSUE TITLE
rethink current implementation to allow more language dialects

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/openaedmap-frontend#86]
current convention of using 2 chars with ISO code will be problematic with some languages like variants of Chinese, Portuguese etc

**Comment by starsep** [comment]
@ttomasz 
Is it still a problem?
I see `zh-Hans` and `zh-Hant` in public/locales for Chinese. It seems to work correctly.
Perhaps README should be improved
> with the 2 letter language ISO 639-1 code

**Comment by ttomasz** [comment]
> Is it still a problem?
To be honest I don't remember what the problem was.
