### ISSUE TITLE
Adding check_date or survey:date automatically

### ISSUE THREAD

**Issue by wzbartczak** [openstreetmap-polska/openaedmap-frontend#90]
It should  add the check_date or survey:date automatically. 

> I had to delete one today which many businesses around believed was still there

_Beta Taster Opinion_

**Comment by Ancymonek** [comment]
Maybe we can add 'Check date' field to Add AED form with current date as default, but with an option to pick past date also? Why if today I am adding AED that I checked yesterday?

**Comment by Ancymonek** [comment]
Avaiable on /DEV. Doesn't look perfect on Firefox because I used native  browser datepicker (Chrome is ok) but works as supossed to. 
![obraz](https://user-images.githubusercontent.com/16021640/205486448-1f770075-630c-4970-b8da-9160a7003ebf.png)
