### ISSUE TITLE
Individual AEDs should be shown earlier for mobile phones

### ISSUE THREAD

**Issue by wzbartczak** [openstreetmap-polska/openaedmap-frontend#91]
>It's a bit of a problem that individual AEDs are not showing on a higher zoom level, because we might end up with duplicate entries.

**Comment by danieldegroot2** [comment]
Hey WZ,

The clustering may not be optimal in general. Feel free to suggest further improvements.

Is there a zoom level you / the beta tester personally prefer?

**Comment by wzbartczak** [comment]
15 will be great

**Comment by Zaczero** [comment]
I suppose this has been resolved
